#!/usr/bin/env sh

cd "$(dirname "$(realpath "$0")")" || exit 1

if [ ! -d .venv ]; then
    python3 -m venv .venv
    . .venv/bin/activate
    pip3 install adafruit-circuitpython-dht
    pip3 install requests
else
    . .venv/bin/activate
fi

python loop.py
