#!/bin/sh

dir=$(dirname "$(readlink -f "$0")")

# Create base directories so that stow wouldn't link them directly
xargs -I {} mkdir -pv "$HOME/{}" < "$dir/dirs.conf"

stow --dir="$dir" --target="$HOME" --verbose "$@" base 

for dir in "$HOME"/.local/share/bashly/*; do
    cd "$dir" || exit 1
    bashly generate -e production --quiet
done
