#!/usr/bin/env sh
# List stow modules for the current system

mods='base git'

case "$(uname -n)" in
    l4)
        mods="base" 
        ;;
    ITP*)
        mods="base"
        ;;
    *)
        mods="$mods" 
        ;;
esac

echo "$mods"
