#!/bin/sh

source=$(dirname "$(readlink -f "$0")")

dirs=$(grep -v '^\(#\|$\)' < "$source/dirs.conf")

# Create base directories so that stow wouldn't link them directly
echo "$dirs" | xargs -I {} mkdir -pv "$HOME/{}"

stow --dir="$source" --target="$HOME" --verbose "$@" base 
