#!/bin/sh

dir=$(dirname "$(readlink -f "$0")")

mkdir -p "$HOME/.config" \
    "$HOME/.local/share" \
    "$HOME/.gnupg" \
    "$HOME/.config/docker"

stow --dir="$dir" --target="$HOME" --verbose base "$@"
