#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export HISTCONTROL=ignoreboth
export HISTSIZE=1000
export HISTFILESIZE=10000
export HISTFILE="$XDG_STATE_HOME"/bash/history

shopt -s checkwinsize
shopt -s histappend
shopt -s autocd

PROMPT_COMMAND='prompt'

prompt() {
    history -a
    echo -e "\e[6 q"
}

# Colors
alias ls='ls --color=auto -h'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias diff='diff --color=auto'
alias tree="tree -C"

PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] '
