#!/bin/bash

[ -z "$1" ] && echo "secure-check [server] [ssh-port]" && exit 1

ssh_port="${2:-22}"

ssh_result=$(timeout 5 ssh "$1" -p "$ssh_port" \
    -o LogLevel=ERROR \
    -o PubkeyAuthentication=no \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null 2>&1)

if [[ "$ssh_result" =~ "Permission denied" ]]; then
    echo "SSH OK $ssh_result"
    exit 0
else
    echo "SSH attempt assertion failed $ssh_result"
    exit 1
fi
