#!/usr/bin/env sh

set -e

if [ -x "$(command -v gitleaks)" ]; then
    gitleaks protect --staged
else
    gum log --level=warn 'Gitleaks is not installed, skipping check'
fi

email=$(git config user.email)

if [ "$email" != "$DOTS_EMAIL" ]; then
    gum log --level=error 'Git user mail is not correct'
    exit 1
fi

scan-for-binaries
