#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset -b

[ -x "$(command -v unclutter )" ] && unclutter --start-hidden &
[ -x "$(command -v numlockx )" ] && numlockx &

[ -x "$(command -v xss-lock)" ] && xss-lock i3lock &
[ -x "$(command -v lxpolkit)" ] && lxpolkit &

[ -x "$(command -v auto-suspend)" ] && auto-suspend &

mkdir -p "$AWESOME_OUTPUT_DIR"
exec awesome >> "$AWESOME_OUTPUT_DIR/out" 2>> "$AWESOME_OUTPUT_DIR/err"
