format = """$line_break\
$hostname\
$directory\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](yellow)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[hostname]
format = '[$hostname](bold red) '
