#!/usr/bin/env bash

timeout=0

[ -n "$1" ] && [ "$1" = '-f' ] && timeout="${2:-5}"

last_checksum=''
text=''
exit_code=0

while true; do
    received=$(curl -sSf \
        -H "$(sat-auth-header)" \
        "$(sat-base-url)/api/dash" \
        2> /dev/null
    )

    exit_code=$?

    checksum=$(echo "$received" | md5sum)

    if [ "$checksum" != "$last_checksum" ]; then
        [ -n "$received" ] && text="$received"

        clear
        echo "$text"

        [ "$exit_code" != 0 ] && echo -e '\033[0;31m---- <!> ----\033[0m'

        last_checksum="$checksum"
    fi

    ([ "$timeout" != 0 ] && sleep "$timeout") || exit 0
done
