#!/bin/bash

if [ -x "$(command -v vim)" ]; then
    export EDITOR=vim
    export VISUAL=vim
fi

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

export PATH="$PATH:$(find "$HOME"/.local/share/scripts/ -type d | paste -sd ':' -)"

[ -x "$(command -v npm)" ] && PATH="$(npm config get prefix)/bin:$PATH"

[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

[ -f "$XDG_CONFIG_HOME/shell/bashrc" ] && . "$XDG_CONFIG_HOME/shell/bashrc"
