[[patterns]]
cmd = "start-tmux-session"
pattern = "~/Repos/*"

[[session]]
name = "llm"
path = "~/.local/state/sessions/llm"
cmd = "tmux new-window -d; ai"

[[session]]
name = "calc"
path = "~/.local/state/sessions/calc"
cmd = "nvim main.calc.php"

[[session]]
name = "_dots"
path = "~/.dots"
cmd = "start-tmux-session"

[[session]]
name = "generic"
path = "~"
cmd = "tmux set status off"

[[session]]
name = "large"
path = "~"
cmd = "tmux set status off"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Notes"
path = "~"
cmd = "nvim NOTES.md"
