[[patterns]]
cmd = "tmux-start-session"
pattern = "~/Repos/*"
cmd = "start-tmux-session"

[[session]]
name = "llm"
path = "~/.local/state/session/llm"
cmd = "opencode --continue"

[[session]]
name = "calc"
path = "~/.local/state/session/calc"
cmd = "nvim main.calc.php"

[[session]]
name = "_dots"
path = "~/.dots"

[[session]]
name = "generic"
path = "~"
cmd = "tmux set status off"

[[session]]
name = "large"
path = "~"
cmd = "tmux set status off"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Notes"
path = "~"
cmd  = "nvim NOTES.md"
