[[patterns]]
cmd = "tmux-start-session"
pattern = "~/Repos/*"

[[session]]
name = "llm"
dir = "~/.local/state/session/llm"
cmd = "opencode --continue"

[[session]]
name = "calc"
dir = "~/.local/state/session/calc"
cmd = "nvim main.calc.php"

[[session]]
name = "_dots"
path = "~/.dots"
