#!/bin/sh
# Upload changes to remote server

[ -z "$1" ] && REMOTE_HOST="$1"
[ -z "$2" ] && REMOTE_ROOT="$2"

for file in $(git diff --name-only); do
    scp "$file" "$REMOTE_HOST:$REMOTE_ROOT/$file"
done

for file in $(git ls-files --others --exclude-standard); do
    scp "$file" "$REMOTE_HOST:$REMOTE_ROOT/$file"
done

ssh "$REMOTE_HOST" "(cd '$REMOTE_ROOT' && php cachetool.phar opcache:reset --cli; php artisan horizon:terminate; php artisan view:cache)"
