#!/bin/bash

set -euo 'pipefail'
set -x

baseurl="$SAT_JOURNAL_BASE_URL"

options=$(curl -sf "$baseurl" \
    | jq -r 'map((.id | tostring) + "\t" + .title + "\t" + (.word_count | tostring) + "w\t" + .created_at + "\t" + .journal.title) | .[]')

options="$options$(printf '\n0\tNew')"

id=$(echo "$options" \
    | tac \
    | column -ts $'\t' \
    | fzf  --delimiter="\t" \
    | awk '{print $1}')

contents=''
[ "$id" != 0 ] && contents=$(curl -sf "$baseurl/$id" | jq -r '.contents')

file=$(mktemp).md
echo "$contents" > "$file"

nvim -c "set nospell | autocmd BufWritePost * !bash -c 'arw $id $file'" "$file"
