#!/bin/bash

set -euo 'pipefail'

state=${SAT_JOURNAL_STATE:-"$XDG_STATE_HOME"/articles}
token=$(<"$state"/token)
url="$SAT_BASE_URL"/api/journals/articles
dir="$1"

if [ -f "$dir"/id ]; then
    method=PUT
    url="$url/$(<"$dir/id")"
else
    method=POST
fi

cp "$dir"/contents.md "$(mktemp -p "$dir" 'XXXXXXX.md')"

markdown=$(<"$dir"/contents.md)
json=$(jq -n --arg k "contents" --arg v "$markdown" '{$k: $v}')

response=$(curl -sSfX "$method" \
    -H "Authorization: Bearer $token" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -d "$json" \
    "$url"
)

echo "$response" | jq '.id' > "$dir/id"
echo "Word count: $(echo "$response" | jq '.word_count')"
