#!/bin/bash

# Access bookmarks and open a browser tab with an optional parameter

list="$XDG_CONFIG_HOME/bookmarks.list"
list_local="$XDG_CONFIG_HOME/bookmarks.local.list"
search_cmd='fzf -i'

items=$(cat "$list" "$list_local" 2> /dev/null)

for p in "$@"
do
    # Editing bookmarks lists
    [ "$p" = '-e' ] && nvim "$list" && exit 0
    [ "$p" = '-el' ] && nvim "$list_local" && exit 0

    # Listing all bookmarks
    [ "$p" = '-l' ] && echo "$items" && exit 0

    [ "$p" = '--rofi' ] && search_cmd='rofi -dmenu'
done

# Use fzf to select one of the URLs
url=$(printf '%s\n' "${items[@]}" | $search_cmd)

# If selection was canceled then exit
[ ! "$url" ] && exit 1

# Extract the text inside the curly braces {}
placeholder=$(echo "$url" | grep -oP '{.*?}' | tr -d '{}')

if [ "$placeholder" ]; then
    # Prompt the user for input to replace the placeholder
    if [[ "$search_cmd" == *'fzf'* ]]; then
        read -rp "$placeholder: " input
    else
        input=$($search_cmd -p "$placeholder: ")
    fi

    # Replace the placeholder with the user input
    url="${url//\{$placeholder\}/$input}"
fi

xdg-open "https://$url"
