#!/usr/bin/env bash
# Check for running background processes

processes=('scp' 'rsync')

if [ "$1" = '-a' ]; then
    processes+=('brew' 'pacman' 'cp' 'rm')
fi

for process in "${processes[@]}"
do
    pgrep -lx "$process"
done
