#!/usr/bin/env sh
# Execute cmd or sh "main" docker container

names=$(docker-compose ps --format '{{.Names}}')

name=$(echo "$names" | grep -i 'fpm\|laravel.test')

# Use first if no matches
[ ! "$name" ] && name=$(echo "$names" | head -n 1)

docker exec -it "$name" "${@:-bash}"
