#!/bin/sh

set -e

cd "$HOME/Repos/dotfiles"

if [ -z "$(git status --porcelain)" ]; then
    gum log --level=info 'No changes are present' >&2
    exit 1
fi

git status
git diff

echo
msg=$(gum input --placeholder 'Commit message')

git add .
git commit -m "${msg:=Update}"
git pull
git push
