#!/bin/sh

set -e

dir="$XDG_DATA_HOME/services"

cd "$dir" || exit 1

# TODO: cleanup
selected=$(ls | fzf)

unit_dir="$dir/$selected"

cd "$unit_dir"

if docker-compose config > /dev/null 2>&1; then
    echo 'Enabling docker service'

    ln -sv "$unit_dir" "$XDG_DATA_HOME/docker-compose/$selected"
    systemctl --user enable "docker-compose@$selected" --now
else
    echo 'Enabling local service'

    systemctl --user enable "local-service@$selected" --now
fi
