#!/usr/bin/env sh

selected_file=$(git ls-files --others --cached --exclude-standard \
    | fzf --preview "bat --color=always {}" --preview-window "~3"
)

[ -n "$selected_file" ] && "$EDITOR" "$selected_file"
