#!/usr/bin/env sh

set -e

interactive=''
no_add=''

while getopts ':in' opt; do
  case ${opt} in
    i) 
        interactive=1
        ;;
    n) 
        no_add=1
        ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

if [ -z "$(git status --porcelain)" ]; then
    gum log --level=error 'No changes are present' >&2
    exit 1
fi

if [ -n "$interactive" ]; then
    msg=$(git log -n 100 --pretty=%B | sed '/^\s*$/d' | fzf)
else
    msg=$(gum input --value="$(git log -1 --pretty=%B)")
fi

[ -z "$no_add" ] && git add .

git commit -m "$msg"
git push
