#!/usr/bin/env sh

set -eu

dir="$XDG_DATA_HOME/password-store"
commit_hook='.git/hooks/post-commit'

if [ ! -d "$dir" ]; then
    git clone -v 'https://github.com/mantas6/password-store.git' "$dir"
fi

cd "$dir"
git branch --set-upstream-to=origin/main main

if [ ! -f "$commit_hook" ]; then
    echo 'Adding commit hook'

    {
        echo '#!/usr/bin/env bash'
        echo ''
        echo 'git push || echo -e "$(tput setaf 1)Git push has failed!$(tput sgr0)\n"'
    } >> "$commit_hook"
fi
