#!/usr/bin/env sh

wait-for-host google.com

[ -x "$(command -v pass)" ] && (pass git pull; pass git push)

(cd "$HOME"/Repos/dotfiles && git pull && ./stow)

[ -x "$(command -v newsboat)" ] && echo "Syncing newsboat..." \
    && newsboat -x reload \
    && newsboat -x print-unread

echo "Clearing trash..."
trash-empty -vf 90

echo "Updating tldr cache..."
tldr -u
