#!/usr/bin/env sh

set -e

note_dir="$HOME/.local/share/notes"
current_file=$(date +%y-%m-%d).md

cd "$note_dir"

if [ ! -d .git ]; then
    echo "Notes repository is not set up at $note_dir" >&2
    exit 1
fi

mode='preview'

while getopts ':e' opt; do
  case ${opt} in
    e)
        mode='edit'
        ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
    esac
done

case ${mode} in
    preview)
        cat "$note_dir"/* | glow -p
        ;;
    edit)
        filename="$note_dir/$current_file"
        sum=$(shasum "$filename" || echo '')

        nvim -c 'set nospell' + "$filename"

        if [ "$sum" != "$(shasum "$filename")" ]; then
            git add "$filename"
            git commit -m "Update $(basename "$filename")"
            git push
        fi
        ;;
esac
