#!/usr/bin/env php
<?php

$words = [
    'skausmas',
    'kančia',
    'pragaras',
    'dykuma', 'sausuma',
    'tuščias gyvenimas',
    'egzistencija',
    'skerdykla',
    'mėsmalė',
    'pabaiga',
    'bekelė',
    'nepavykę santykiai',
    'pabaiga be pradžios',
    'depresija',
    'demonai',
    'velniai',
    'trauma',
    'klaidos',
    'vienišumas',
    'pagalbos šauksmas',
    'širdies skausmas',
    'skilimas',
    'puvimas',
    'šlapdriba',
    'pasėkmės',
];

$joins = [
    'nes',
    'dėl to kad',
    'ir',
    'po to',
];

function sentence(array $words, array $joins) {
    $sentence = [];

    shuffle($words);
    shuffle($joins);

    $sentence = array_slice($words, 0, 2);

    return ucfirst(implode(', '.$joins[0].' ', $sentence));
}

$paragraph = range(1, rand(8,12));

$paragraph = array_map(fn () => sentence($words, $joins), $paragraph);

echo implode('. ', $paragraph) . '.';
