#!/usr/bin/env php
<?php

$words = [
    'skausmas',
    'kančia',
    'pragaras',
    'dykuma',
    'tuščias gyvenimas',
    'egzistencija',
    'skerdykla',
    'mėsmalė',
    'pabaiga',
    'nepavykę santykiai',
    'pabaiga be pradžios',
    'depresija',
    'demonai',
    'velniai',
    'trauma',
    'klaidos',
    'vienišumas',
    'pagalbos šauksmas',
    'širdies skausmas',
    'skilimas',
    'puvimas',
    'šlapdriba',
    'pasėkmės',
    'tamsa',
];

$paragraphs = array_fill(0, $argv[1] ?? 1, $words);

$paragraphs = array_map(
    callback: function ($words) {
        shuffle($words);

        $sentences = [];

        while (count($words) > 0) {
            $sentence = array_splice($words, 0, rand(2, 4));

            $sentences[] = ucfirst(implode(' ', $sentence));
        }

        return implode('. ', $sentences) . '.';
    },

    array: $paragraphs,
);

$paragraphs = array_chunk(
    array: $paragraphs,
    length: round(count($paragraphs) / ($argv[2] ?? 1)),
);

$paragraphs = array_map(
    callback: fn ($sentences) => implode('', $sentences),
    array: $paragraphs,
);

echo implode("\n\n", $paragraphs);
