#!/bin/sh
# Override remote variable with production ones

export REMOTE_USER="$REMOTE_PROD_USER"
export REMOTE_HOST="$REMOTE_PROD_HOST"

if [ "$1" = '-f' ]; then
    shift
    export REMOTE_ROOT="$REMOTE_PROD_ROOT"
else
    export REMOTE_ROOT="$REMOTE_STG_ROOT"
fi

gum confirm --no-show-help 'Run cmd in production?' || exit 1

"$@"
