#!/usr/bin/env bash

grep -oP '^[^, ]+' ~/.ssh/known_hosts | while read -r line; do 
    line=$(echo "$line" | sed 's/\[\|\]//g')
    if [[ $line == *:* ]]; then
        # Split hostname/IP and port
        host=$(echo "$line" | awk -F: '{print $1}')
        port=$(echo "$line" | awk -F: '{print $2}')
    else
        host="$line"
        port=22
    fi

    secure-check "$host" "$port"
done
