#!/bin/sh
# Tmux session start hook - ran after new session creation

if [ -d '.git' ]; then
    tmux rename-window 'vi'
    tmux send-keys 'nvim .' C-m

    tmux new-window -n 'ex'

    tmux new-window -n 'git'
    tmux send-keys 'lazygit' C-m

    tmux select-window -t 'vi'
elif [ "$(pwd)" = "$HOME/Downloads" ]; then
    [ -x "$(command -v eza)" ] && eza --icons --group-directories-first -l
elif [ "$(pwd)" = "$HOME" ]; then
    [ -x "$(command -v fastfetch)" ] && fastfetch
fi
