#!/bin/sh
# Tmux session start hook - ran after new session creation

if [ -d '.git' ]; then
    tmux rename-window 'vi'
    tmux send-keys 'nvim .' C-m

    tmux new-window -n 'ex'
    tmux new-window -n 'git' 'lazygit'

    tmux select-window -t 'vi'
elif [ "$(pwd)" = "$HOME/Downloads" ]; then
    eza --icons --group-directories-first -l
fi
