#!/bin/sh
# Upload changes to remote server

#[ -z "$1" ] && REMOTE_HOST="$1"
#[ -z "$2" ] && REMOTE_ROOT="$2"

host="$REMOTE_USER@$REMOTE_HOST"

for file in $(git diff --name-only); do
    scp "$file" "$host:$REMOTE_ROOT/$file"
done

for file in $(git ls-files --others --exclude-standard); do
    scp "$file" "$host:$REMOTE_ROOT/$file"
done

ssh "$host" "(cd '$REMOTE_ROOT' && php cachetool.phar opcache:reset --cli; php artisan horizon:terminate; php artisan view:cache)"
