#!/usr/bin/env bash
# Upload changes to remote server

#[ -z "$1" ] && REMOTE_HOST="$1"
#[ -z "$2" ] && REMOTE_ROOT="$2"

host="$REMOTE_USER@$REMOTE_HOST"

files=()

for file in $(git diff --name-only); do
    files+=("$file")
    # scp "$file" "$host:$REMOTE_ROOT/$file"
done

for file in $(git ls-files --others --exclude-standard); do
    files+=("$file")
    # scp "$file" "$host:$REMOTE_ROOT/$file"
done

rsync -RPrzcav "${files[@]}" "$host:$REMOTE_ROOT"

ssh "$host" "(cd '$REMOTE_ROOT' && php cachetool.phar opcache:reset --cli; php artisan horizon:terminate; php artisan view:cache)"
