#!/bin/sh

filename="/backup_$(date +%y%m%d%H%M).tar.gz"

sudo tar czf "$filename" \
    --exclude="$filename" \
    --exclude=/dev \
    --exclude=/mnt \
    --exclude=/proc \
    --exclude=/sys \
    --exclude=/tmp \
    --exclude=/media \
    --exclude=/lost+found \
    --exclude=/run \
    /
