#!/bin/sh
# Live PHP code evaluation from vim buffer

# cd "$(git rev-parse --show-toplevel)" || exit 1

index="$(pwd)/.tinker-index.php"
buffer="$(pwd)/.tinker-buffer.php"

# Evaluate in remote host
if [ "$1" = '-s' ]; then
    scp "$index" "$buffer" "$REMOTE_HOST:$REMOTE_ROOT"
    ssh -tt "$REMOTE_HOST" "cd $REMOTE_ROOT && php .tinker-index.php"
    exit 0
fi

echo '<?php' >> "$buffer"

cat <<EOF > "$index"
<?php

require __DIR__.'/vendor/autoload.php';

\$app = require_once __DIR__.'/bootstrap/app.php';

\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);

\$status = \$kernel->handle(
    \$input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\BufferedOutput
);

\$result = require './$(basename "$buffer")';

dump(\$result);

\$kernel->terminate(\$input, \$status);
EOF

nvim -c "command! Remote only | vsp | terminal bash -c 'tin -s'" \
    -c "set nospell | set scrollback=100000 | set splitright" \
    -c "autocmd BufWritePost * only | vsp | terminal de php $(basename "$index")" "$buffer"

rm "$buffer"
rm "$index"
