#!/bin/sh
# Live PHP code evaluation from vim buffer

# cd "$(git rev-parse --show-toplevel)" || exit 1

if [ ! -f composer.json ]; then
    echo 'Current directory is not an PHP application' >&2
    exit 1
fi

index="$(pwd)/.tinker-index.php"
buffer="$(pwd)/.tinker-buffer.php"

write_cmd="de php $(basename "$index")"

# Evaluate in remote host
if [ "$1" = '-x' ]; then
    host="$REMOTE_USER@$REMOTE_HOST"
    rsync -av "$index" "$buffer" "$host:$REMOTE_ROOT"
    ssh -tt "$host" "cd $REMOTE_ROOT && php .tinker-index.php"
    exit 0
fi

[ "$1" = '-r' ] && write_cmd='tin -x'

[ ! -f "$buffer" ] && echo '<?php' >> "$buffer"

cat <<EOF > "$index"
<?php

require __DIR__.'/vendor/autoload.php';

\$app = require_once __DIR__.'/bootstrap/app.php';

\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);

\$status = \$kernel->handle(
    \$input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\BufferedOutput
);

\$result = require './$(basename "$buffer")';

dump(\$result);

\$kernel->terminate(\$input, \$status);
EOF

nvim -c "set nospell | set scrollback=100000 | set splitright" \
    -c "autocmd BufWritePost * only | vsp | terminal $write_cmd" "$buffer"

rm "$index"
