#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

data=$(fastfetch -s disk --format json --disk-folders '/')
used=$(echo "$data" | jq '.[0].result.[0].bytes.used')
total=$(echo "$data" | jq '.[0].result.[0].bytes.total')

percent=$((used / total))

sketchybar --set "$NAME" icon="" label="$percent%"
