#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

mem=$(fastfetch -s memory --format json | jq -r '(.[0].result.used / 1024 / 1024 / 1024 * 10 | round) / 10')
swap=$(fastfetch -s swap --format json | jq -r '(.[0].result.used / 1024 / 1024 / 1024 * 10 | round) / 10')

sketchybar --set "$NAME" icon="" label="${mem}G/${swap}G"
