#!/bin/bash

set -euo 'pipefail'

baseurl="$SAT_BASE_URL"/api/journals/articles
state=${SAT_JOURNAL_STATE:-"$XDG_STATE_HOME"/sat}
token=$(<"$state"/token)

options=$(curl -sSfH "Authorization: Bearer $token" "$baseurl" \
    | jq -r 'map((.id | tostring) + "\t" + .title + "\t" + (.word_count | tostring) + "w\t" + .created_at + "\t" + .journal.title) | .[]')

options="$options$(printf '\n0\tNew')"

id=$(echo "$options" \
    | tac \
    | column -ts $'\t' \
    | fzf  --delimiter="\t" \
    | awk '{print $1}')

mkdir -p "$state/tmp"

current=$(mktemp -dp "$state/tmp" 'XXXXXXXXXX')
file="$current"/contents.md

if [ "$id" != 0 ]; then
    contents=$(curl -sSfH "Authorization: Bearer $token" "$baseurl/$id" | jq -r '.contents')

    echo "$id" > "$current"/id
    echo "$contents" > "$file"
fi

nvim -c "set nospell | autocmd BufWritePost * !bash -c 'arw $current'" "$file"

[ ! -f "$file" ] && echo 'Article discarded'
