#!/usr/bin/env sh
# Execute cmd or sh "main" docker container

names=$(docker compose ps --format '{{.Names}}')

name=$(echo "$names" | grep -i 'fpm\|laravel.test')

# Use first if no matches
[ ! "$name" ] && name=$(echo "$names" | head -n 1)

if [ -t 0 ]; then
    flags='-it'
else
    flags='-i'
fi

docker exec "$flags" "$name" "${@:-bash}"
