#!/usr/bin/env bash
# Upload changes to remote server

#[ -z "$1" ] && REMOTE_HOST="$1"
#[ -z "$2" ] && REMOTE_ROOT="$2"

host="$REMOTE_USER@$REMOTE_HOST"

if [ -z "$1" ]; then
    files=()

    for file in $(git diff --name-only); do
        files+=("$file")
    done

    for file in $(git ls-files --others --exclude-standard); do
        files+=("$file")
    done
else
    files=("$@")
fi

rsync -RPrzcav "${files[@]}" "$host:$REMOTE_ROOT"

if [ -f artisan ]; then
    ssh "$host" "(cd '$REMOTE_ROOT' && php cachetool.phar opcache:reset --cli; php artisan horizon:terminate; php artisan optimize)"
fi
