#!/usr/bin/env sh

url=$1

old=$(mktemp)
new=$(mktemp)

# Baseline
curl -s "$url" > "$new"
curl -s "$url" > "$old"

while true; do
    proposed=$(curl -sf "$url")

    [ -n "$proposed" ] && new="$proposed"

    if ! cmp -s "$old" "$new"; then
      exit 0
    fi

    sleep 1
done
