services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      TELEMETRY: true
      DB_TYPE: sqlite
      WEBPORT: 8080
    ports:
      - "6001:8080"
    volumes:
      - './data:/database'
