#!/bin/bash

# Editor
export MANPAGER="nvim +Man! -c 'set nospell'"
export EDITOR="nvim"
export VISUAL="nvim"
export DIFFPROG="nvim -d"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

[ "$(uname)" = "Darwin" ] && export XDG_RUNTIME_DIR="$HOME/Library/Caches/TemporaryItems"

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export AWESOME_OUTPUT_DIR="$XDG_CACHE_HOME/awesome"

# Homebrew rootless
if [ -d "$HOME/.local/brew" ]; then
    export HOMEBREW_PREFIX="$HOME/.local/brew"
    export HOMEBREW_MAKE_JOBS=2
    export PATH="$HOMEBREW_PREFIX/bin:$PATH"

    [ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ] \
        && source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
fi

if [ -x "$(command -v gem)" ]; then
    export GEM_HOME=$(gem env user_gemhome)
    export PATH="$PATH:$GEM_HOME/bin"
fi

# Other
if [ "$(uname)" != "Darwin" ]; then
    export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
    export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
fi

export ATAC_MAIN_DIR="$XDG_CONFIG_HOME/atac"
export ATAC_KEY_BINDINGS="$XDG_CONFIG_HOME/atac/key.toml"

export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export PASSWORD_STORE_CHARACTER_SET="[:alnum:]"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export VIT_DIR="$XDG_CONFIG_HOME/vit"

export MOZ_USE_XINPUT2=1
export QT_QPA_PLATFORMTHEME=qt6ct

[ -f "$XDG_CONFIG_HOME/shell/local/profile" ] && . "$XDG_CONFIG_HOME/shell/local/profile"

export PATH="$PATH:$(find "$HOME"/.local/share/scripts/ -type d | paste -sd ':' -)"

[ -x "$(command -v npm)" ] && PATH="$(npm config get prefix)/bin:$PATH"

[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

[ -d "$HOME/.local/share/bashly/art/bin" ] && export PATH="$HOME/.local/share/bashly/art/bin:$PATH"

[ -f "$XDG_CONFIG_HOME/shell/bashrc" ] && . "$XDG_CONFIG_HOME/shell/bashrc"

if [ -x "$(command -v startx)" ] && [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
    echo "Start time: $(date)" >> "$XDG_CACHE_HOME/Xoutput"
    exec startx "$XINITRC" &>> "$XDG_CACHE_HOME/Xoutput"
fi

