#!/usr/bin/env bash

state_home=${XDG_STATE_HOME:-"$HOME/.local/state"}
state=${SAT_JOURNAL_STATE:-"$state_home"/sat}
token=$(cat "$state"/token)
base_url=$(cat "$state"/url)

curl -sSfL \
    -H "Authorization: Bearer $token" \
    -X POST "$base_url/api/machine/$(uname -n)" \
    > /dev/null
