#!/usr/bin/env sh

set -e

state=${SAT_JOURNAL_STATE:-"$XDG_STATE_HOME"/sat}

[ ! -d "$state" ] && mkdir -pv "$state"

if [ ! -f "$state/url" ]; then
    base_url=$(gum input --placeholder 'Base url' --no-show-help)
    echo "$base_url" > "$state/url"
fi

[ -f "$state/token" ] && gum log --level warn 'Token is already defined'

token=$(gum input --placeholder 'Token' --no-show-help)
echo "$token" > "$state/token"

gum log --level info 'Token added successfuly'
