name: "Flake check"
on:
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
      - 'nix/**'
      - 'opt/wolf/**'
      - '.github/workflows/flake-check.yml'
  push:
    branches: [main]
    paths:
      - '**.nix'
      - 'flake.lock'
      - 'nix/**'
      - 'opt/wolf/**'
      - '.github/workflows/flake-check.yml'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check --all-systems
